// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtPIxFkbzNtZ8_9ADNmb_6IriS_0jD4kE',
    appId: '1:140229310127:web:05f48494c489bd048b065a',
    messagingSenderId: '140229310127',
    projectId: 'zinzi-fcm2',
    authDomain: 'zinzi-fcm2.firebaseapp.com',
    storageBucket: 'zinzi-fcm2.firebasestorage.app',
    measurementId: 'G-HFLZEDCKZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMOYWwAVntsxg6cfY1EHa_q4Xt3zlliFM',
    appId: '1:140229310127:android:055b6b0182817a148b065a',
    messagingSenderId: '140229310127',
    projectId: 'zinzi-fcm2',
    storageBucket: 'zinzi-fcm2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9d5jyRerS6NvzfXCyP5PnOLwoq63Vgs0',
    appId: '1:140229310127:ios:98af5a73ddf7cf948b065a',
    messagingSenderId: '140229310127',
    projectId: 'zinzi-fcm2',
    storageBucket: 'zinzi-fcm2.firebasestorage.app',
    iosBundleId: 'com.chwezicreatives.zinzi2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9d5jyRerS6NvzfXCyP5PnOLwoq63Vgs0',
    appId: '1:140229310127:ios:98af5a73ddf7cf948b065a',
    messagingSenderId: '140229310127',
    projectId: 'zinzi-fcm2',
    storageBucket: 'zinzi-fcm2.firebasestorage.app',
    iosBundleId: 'com.chwezicreatives.zinzi2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtPIxFkbzNtZ8_9ADNmb_6IriS_0jD4kE',
    appId: '1:140229310127:web:b68d87bcb5c88c978b065a',
    messagingSenderId: '140229310127',
    projectId: 'zinzi-fcm2',
    authDomain: 'zinzi-fcm2.firebaseapp.com',
    storageBucket: 'zinzi-fcm2.firebasestorage.app',
    measurementId: 'G-P1LSJPFLX2',
  );
}
