# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods analytics sends logs at the end of the install phase.
# Set this to false to disable it.
# ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner.xcodeproj'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_application_path = '../..'
  # This line loads the plugins from the .flutter-plugins file
  load File.join(flutter_application_path, '.flutter-plugins')

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end
end